In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
file_path = "../data/raw/yellow_tripdata_2025-01.parquet"

df = pd.read_parquet(file_path)

print("Shape:", df.shape)

df.head()

Shape: (3475226, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [3]:
df.columns.tolist()

['VendorID',
 'tpep_pickup_datetime',
 'tpep_dropoff_datetime',
 'passenger_count',
 'trip_distance',
 'RatecodeID',
 'store_and_fwd_flag',
 'PULocationID',
 'DOLocationID',
 'payment_type',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'improvement_surcharge',
 'total_amount',
 'congestion_surcharge',
 'Airport_fee',
 'cbd_congestion_fee']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 493.5 MB

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
VendorID,3475226.0,NaN,NaN,NaN,1.785428,1.0,2.0,2.0,2.0,7.0,0.426328
tpep_pickup_datetime,3475226,NaN,NaN,NaN,2025-01-17 11:02:55.910964,2024-12-31 20:47:55,2025-01-10 07:59:01,2025-01-17 15:41:33,2025-01-24 19:34:06,2025-02-01 00:00:44,NaN
tpep_dropoff_datetime,3475226,NaN,NaN,NaN,2025-01-17 11:17:56.997901,2024-12-18 07:52:40,2025-01-10 08:15:29.500000,2025-01-17 15:59:34,2025-01-24 19:48:31,2025-02-01 23:44:11,NaN
passenger_count,2935077.0,NaN,NaN,NaN,1.297859,0.0,1.0,1.0,1.0,9.0,0.75075
trip_distance,3475226.0,NaN,NaN,NaN,5.855126,0.0,0.98,1.67,3.1,276423.57,564.6016
RatecodeID,2935077.0,NaN,NaN,NaN,2.482535,1.0,1.0,1.0,1.0,99.0,11.632772
store_and_fwd_flag,2935077,2,N,2927431,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PULocationID,3475226.0,NaN,NaN,NaN,165.191576,1.0,132.0,162.0,234.0,265.0,64.529483
DOLocationID,3475226.0,NaN,NaN,NaN,164.125177,1.0,113.0,162.0,234.0,265.0,69.401686
payment_type,3475226.0,NaN,NaN,NaN,1.036623,0.0,1.0,1.0,1.0,5.0,0.701333
fare_amount,3475226.0,NaN,NaN,NaN,17.081803,-900.0,8.6,12.11,19.5,863372.12,463.472918
extra,3475226.0,NaN,NaN,NaN,1.317737,-7.5,0.0,0.0,2.5,15.0,1.861509
mta_tax,3475226.0,NaN,NaN,NaN,0.478099,-0.5,0.5,0.5,0.5,10.5,0.137462
tip_amount,3475226.0,NaN,NaN,NaN,2.959813,-86.0,0.0,2.45,3.93,400.0,3.779681
tolls_amount,3475226.0,NaN,NaN,NaN,0.449308,-126.94,0.0,0.0,0.0,170.94,2.002582
improvement_surcharge,3475226.0,NaN,NaN,NaN,0.954795,-1.0,1.0,1.0,1.0,1.0,0.278194
total_amount,3475226.0,NaN,NaN,NaN,25.611292,-901.0,15.2,19.95,27.78,863380.37,463.658478
congestion_surcharge,2935077.0,NaN,NaN,NaN,2.225237,-2.5,2.5,2.5,2.5,2.5,0.903993
Airport_fee,2935077.0,NaN,NaN,NaN,0.123911,-1.75,0.0,0.0,0.0,6.75,0.472509
cbd_congestion_fee,3475226.0,NaN,NaN,NaN,0.483409,-0.75,0.0,0.75,0.75,0.75,0.361931

In [6]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nDuplicates:")
print(df.duplicated().sum())

print("\nMissing values:")
print(
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

Rows: 3475226
Columns: 20

Duplicates:
0

Missing values:
Airport_fee              540149
passenger_count          540149
congestion_surcharge     540149
RatecodeID               540149
store_and_fwd_flag       540149
VendorID                      0
mta_tax                       0
total_amount                  0
improvement_surcharge         0
tolls_amount                  0
tip_amount                    0
fare_amount                   0
extra                         0
tpep_pickup_datetime          0
payment_type                  0
DOLocationID                  0
PULocationID                  0
trip_distance                 0
tpep_dropoff_datetime         0
cbd_congestion_fee            0
dtype: int64

In [7]:
missing = (
    df.isnull()
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

missing

Airport_fee              15.542845
passenger_count          15.542845
congestion_surcharge     15.542845
RatecodeID               15.542845
store_and_fwd_flag       15.542845
VendorID                  0.000000
mta_tax                   0.000000
total_amount              0.000000
improvement_surcharge     0.000000
tolls_amount              0.000000
tip_amount                0.000000
fare_amount               0.000000
extra                     0.000000
tpep_pickup_datetime      0.000000
payment_type              0.000000
DOLocationID              0.000000
PULocationID              0.000000
trip_distance             0.000000
tpep_dropoff_datetime     0.000000
cbd_congestion_fee        0.000000
dtype: float64

In [8]:
numeric_cols = [
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "tip_amount",
    "tolls_amount",
    "total_amount"
]

df[numeric_cols].describe(
    percentiles=[0.01, 0.05, 0.5, 0.95, 0.99]
).T

,count,mean,std,min,1%,5%,50%,95%,99%,max
passenger_count,2935077.0,1.297859,0.750750,0.00,1.0,1.00,1.00,3.00,5.00,9.00
trip_distance,3475226.0,5.855126,564.601600,0.00,0.0,0.39,1.67,11.83,19.50,276423.57
fare_amount,3475226.0,17.081803,463.472918,-900.00,-10.7,3.70,12.11,52.00,72.30,863372.12
tip_amount,3475226.0,2.959813,3.779681,-86.00,0.0,0.00,2.45,10.00,17.19,400.00
tolls_amount,3475226.0,0.449308,2.002582,-126.94,0.0,0.00,0.00,6.94,6.94,170.94
total_amount,3475226.0,25.611292,463.658478,-901.00,-15.7,8.75,19.95,74.00,102.92,863380.37

In [9]:
df["trip_duration_minutes"] = (
    df["tpep_dropoff_datetime"]
    - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

In [10]:
df["trip_duration_minutes"].describe(
    percentiles=[0.01, 0.05, 0.5, 0.95, 0.99]
)

count    3.475226e+06
mean     1.501812e+01
std      3.871358e+01
min     -5.147232e+04
1%       6.666667e-01
5%       3.366667e+00
50%      1.170000e+01
95%      3.620000e+01
99%      5.891667e+01
max      5.626317e+03
Name: trip_duration_minutes, dtype: float64

In [11]:
print(
    "Zero/negative duration:",
    (df["trip_duration_minutes"] <= 0).sum()
)

print(
    "Trips > 3 hours:",
    (df["trip_duration_minutes"] > 180).sum()
)

Zero/negative duration: 2051
Trips > 3 hours: 1377

In [12]:
df["avg_speed_mph"] = (
    df["trip_distance"] /
    (df["trip_duration_minutes"] / 60)
)

In [13]:
df["avg_speed_mph"].describe(
    percentiles=[0.50, 0.90, 0.95, 0.99, 0.999]
)

/Users/unnatiagrawal/nyc-taxi-intelligence/.venv/lib/python3.14/site-packages/pandas/core/nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    3.474534e+06
mean              inf
std               NaN
min     -6.436800e+04
50%      9.519231e+00
90%      1.946275e+01
95%      2.511975e+01
99%      3.574468e+01
99.9%    5.001457e+01
max               inf
Name: avg_speed_mph, dtype: float64

In [14]:
print(
    "Speed > 80 mph:",
    (df["avg_speed_mph"] > 80).sum()
)

Speed > 80 mph: 2217

In [15]:
zones = pd.read_csv(
    "../data/raw/taxi_zone_lookup.csv"
)

zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [16]:
zones.shape

(265, 4)

In [17]:
zones["Borough"].value_counts()

Borough
Queens           69
Manhattan        69
Brooklyn         61
Bronx            43
Staten Island    20
EWR               1
Unknown           1
Name: count, dtype: int64

In [18]:
test = df[
    [
        "PULocationID",
        "DOLocationID",
        "tpep_pickup_datetime",
        "trip_distance",
        "total_amount"
    ]
].head(1000)

In [19]:
test = test.merge(
    zones[["LocationID", "Borough", "Zone"]],
    left_on="PULocationID",
    right_on="LocationID",
    how="left"
)

In [20]:
test = test.rename(
    columns={
        "Borough": "pickup_borough",
        "Zone": "pickup_zone"
    }
)

test[
    [
        "PULocationID",
        "pickup_borough",
        "pickup_zone"
    ]
].head(20)

    PULocationID pickup_borough                    pickup_zone
0            229      Manhattan  Sutton Place/Turtle Bay North
1            236      Manhattan          Upper East Side North
2            141      Manhattan                Lenox Hill West
3            244      Manhattan       Washington Heights South
4            244      Manhattan       Washington Heights South
5            239      Manhattan          Upper West Side South
6            170      Manhattan                    Murray Hill
7            234      Manhattan                       Union Sq
8            148      Manhattan                Lower East Side
9            237      Manhattan          Upper East Side South
10           237      Manhattan          Upper East Side South
11           263      Manhattan                 Yorkville West
12           236      Manhattan          Upper East Side North
13           229      Manhattan  Sutton Place/Turtle Bay North
14           141      Manhattan                Lenox Hill West
15           158      Manhattan  Meatpacking/West Village West
16           164      Manhattan                  Midtown South
17            79      Manhattan                   East Village
18            79      Manhattan                   East Village
19           246      Manhattan      West Chelsea/Hudson Yards

In [21]:
quick_demand = (
    test.groupby("pickup_zone")
        .size()
        .sort_values(ascending=False)
        .head(10)
)

quick_demand

pickup_zone
Upper East Side South            57
East Village                     54
Lincoln Square East              52
Upper West Side South            50
Yorkville West                   44
Sutton Place/Turtle Bay North    44
Lenox Hill West                  34
West Village                     33
Union Sq                         31
Gramercy                         30
dtype: int64